#
# Please setup the ssh keys from node1 to node1, 2, 3 and 4 from your desktop/laptop
#
- hosts: cluster
  become: yes
  gather_facts: no
  tasks:
  - name: remove unattended-upgrades
    apt:
      name: unattended-upgrades
      state: absent
  
  - name: remove snapd
    apt:
      name: snapd
      state: absent

  - name: apt-get update
    apt:
      update_cache: yes

  - name: apt-get upgrade
    apt:
      only_upgrade: yes

  - name: apt-get dist-upgrade
    apt:
      upgrade: dist

  - name: apt-get autoclean
    apt:
      autoclean: yes

  - name: apt-get autoremove
    apt:
      autoremove: yes

  - name: retrieve wifi settings
    include_vars:
      file: wifi.yml
      name: wifi

  - name: set network config
    copy:
      content: |
        network:
          version: 2
          ethernets:
            eth0:
              dhcp4: false
              optional: true
              addresses: [{{ eth0_ip }}/24]
          wifis:
            wlan0:
              dhcp4: true
              optional: true
              access-points:
                "{{ wifi.accesspoint }}":
                  password: "{{ wifi.password }}"
      dest: /etc/netplan/01-network-card.yaml
    register: config

  - name: remove initial netplan config
    file:
      path: /etc/netplan/50-cloud-init.yaml
      state: absent

  - name: netplan generate
    command: netplan generate
    when: config.changed

  - name: netplan activate
    command: netplan apply
    when: config.changed
    
  - name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi (Thanks k3s!)
    lineinfile:
      path: /boot/firmware/cmdline.txt
      backrefs: yes
      regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
      line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    register: cgroups

  - name: reboot if needed 
    reboot:
    when: cgroups.changed