---

- hosts: node1
  become: yes
  gather_facts: no
  tasks:
  - name: Activate crds
    command: kubectl create -f https://download.elastic.co/downloads/eck/1.8.0/crds.yaml
    ignore_errors: true
  
  - name: Activate operator
    command: kubectl apply -f https://download.elastic.co/downloads/eck/1.8.0/operator.yaml
