---

- hosts: node1
  become: yes
  gather_facts: no
  tasks:
#
# Deploy elasticsearch
#
  - name: Create _elasticsearch.yml
    become_user: ubuntu
    ansible.builtin.copy:
      content: |
        apiVersion: elasticsearch.k8s.elastic.co/v1
        kind: Elasticsearch
        metadata:
          name: quickstart
        spec:
          version: 7.15.0
          nodeSets:
          - name: default
            count: 3
            config:
              node.store.allow_mmap: false  
      dest: /home/ubuntu/kubespray/_elasticsearch.yml
    register: createyml

  - name: Deploy elasticsearch
    become_user: ubuntu
    ansible.builtin.shell: kubectl apply -f kubespray/_elasticsearch.yml
    when: createyml.changed
#
# Create NodePort quickstart-es-http svc
#
  - name: Create _nodeport-quickstart-es-http.yml
    become_user: ubuntu
    ansible.builtin.copy:
      content: |
        apiVersion: v1
        kind: Service
        metadata:
          labels:
            common.k8s.elastic.co/type: elasticsearch
            elasticsearch.k8s.elastic.co/cluster-name: quickstart
          name: nodeport-quickstart-es-http
          namespace: default
        spec:
          externalTrafficPolicy: Cluster
          ports:
          - name: https
            port: 9200
            protocol: TCP
            targetPort: 9200
            nodePort: 30002
          selector:
            common.k8s.elastic.co/type: elasticsearch
            elasticsearch.k8s.elastic.co/cluster-name: quickstart
          sessionAffinity: None
          type: NodePort
        status:
          loadBalancer: {}
      dest: /home/ubuntu/kubespray/_nodeport-quickstart-es-http.yml
    register: svc
#
# Activate nodeport-quickstart-es-http dashboard svc
#
  - name: Activate nodeport-quickstart-es-http dashboard svc
    become_user: ubuntu
    ansible.builtin.shell: kubectl apply -f kubespray/_nodeport-quickstart-es-http.yml
    when: svc.changed