---

#
# Deploy kubernetes metricbeat
#
- hosts: node1
  become: yes
  gather_facts: no
  tasks:
  - name: create _kubernetes-metricbeat.yml
    become_user: ubuntu
    ansible.builtin.copy:
      content: |
        apiVersion: beat.k8s.elastic.co/v1beta1
        kind: Beat
        metadata:
          name: metricbeat
        spec:
          type: metricbeat
          version: 7.15.0
          elasticsearchRef:
            name: quickstart
          kibanaRef:
            name: quickstart
          config:
            metricbeat:
              autodiscover:
                providers:
                - hints:
                    default_config: {}
                    enabled: "true"
                  host: ${NODE_NAME}
                  type: kubernetes
              modules:
              - module: system
                period: 10s
                metricsets:
                - cpu
                - load
                - memory
                - network
                - process
                - process_summary
                process:
                  include_top_n:
                    by_cpu: 5
                    by_memory: 5
                processes:
                - .*
              - module: system
                period: 1m
                metricsets:
                - filesystem
                - fsstat
                processors:
                - drop_event:
                    when:
                      regexp:
                        system:
                          filesystem:
                            mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib)($|/)
              - module: kubernetes
                period: 10s
                host: ${NODE_NAME}
                hosts:
                - https://${NODE_NAME}:10250
                bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                ssl:
                  verification_mode: none
                metricsets:
                - node
                - system
                - pod
                - container
                - volume
                add_metadata: true

              # State metrics from kube-state-metrics service:
              - module: kubernetes
                enabled: true
                metricsets:
                  - state_node
                  - state_daemonset
                  - state_deployment
                  - state_replicaset
                  - state_statefulset
                  - state_pod
                  - state_container
                  - state_job
                  - state_cronjob
                  - state_resourcequota
                  - state_service
                  - state_persistentvolume
                  - state_persistentvolumeclaim
                  - state_storageclass
                period: 10s
                hosts: ["kube-state-metrics.kube-system.svc:8080"]
                add_metadata: true

              - module: kubernetes
                enabled: true
                metricsets:
                  - apiserver
                hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
                bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                ssl.certificate_authorities:
                  - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                period: 30s

            processors:
            - add_cloud_metadata: {}
            - add_host_metadata: {}
          daemonSet:
            podTemplate:
              spec:
                serviceAccountName: metricbeat
                automountServiceAccountToken: true # some older Beat versions are depending on this settings presence in k8s context
                containers:
                - args:
                  - -e
                  - -c
                  - /etc/beat.yml
                  - -system.hostfs=/hostfs
                  name: metricbeat
                  volumeMounts:
                  - mountPath: /hostfs/sys/fs/cgroup
                    name: cgroup
                  - mountPath: /var/run/docker.sock
                    name: dockersock
                  - mountPath: /hostfs/proc
                    name: proc
                  env:
                  - name: NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                dnsPolicy: ClusterFirstWithHostNet
                hostNetwork: true # Allows to provide richer host metadata
                securityContext:
                  runAsUser: 0
                terminationGracePeriodSeconds: 30
                volumes:
                - hostPath:
                    path: /sys/fs/cgroup
                  name: cgroup
                - hostPath:
                    path: /var/run/docker.sock
                  name: dockersock
                - hostPath:
                    path: /proc
                  name: proc
        ---
        # permissions needed for metricbeat
        # source: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: metricbeat
        rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          - namespaces
          - events
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups: 
          - batch
          resources:
          - jobs
          verbs:
          - get
          - list
          - watch          
        - apiGroups:
          - "extensions"
          resources:
          - replicasets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - statefulsets
          - deployments
          - replicasets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes/stats
          verbs:
          - get
        - nonResourceURLs:
          - /metrics
          verbs:
          - get
        ---
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: metricbeat
          namespace: default
        --- 
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: metricbeat
        subjects:
        - kind: ServiceAccount
          name: metricbeat
          namespace: default
        roleRef:
          kind: ClusterRole
          name: metricbeat
          apiGroup: rbac.authorization.k8s.io
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          labels:
            app.kubernetes.io/component: exporter
            app.kubernetes.io/name: kube-state-metrics
            app.kubernetes.io/version: 2.2.1
          name: kube-state-metrics
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: kube-state-metrics
        subjects:
        - kind: ServiceAccount
          name: kube-state-metrics
          namespace: kube-system
      dest: /home/ubuntu/kubespray/_kubernetes-metricbeat.yml
    register: createyml
  
  - name: install kubernetes-metricbeat
    command: kubectl apply -f /home/ubuntu/kubespray/_kubernetes-metricbeat.yml
    when: createyml.changed
